### ISSUE TITLE
Engine outfit categorized wrong Hai space

### ISSUE THREAD

**Issue by Naasaan** [endless-sky/endless-sky-wiki#83]
I found that the Reverse thrusters in Hai space cant be installed if you're low on weapons capacity.
See attached screenshots.

I was trying to fix it in the "hai outfits.txt" but could not find the reverse thrusters listed there.

![Screenshot from 2024-12-28 00 56 35](https://github.com/user-attachments/assets/aa341736-63cf-4955-81fd-f0120b18ee97)
![Screenshot from 2024-12-28 00 57 05](https://github.com/user-attachments/assets/65b965ce-156d-4ef9-81d7-8cd4aafe3981)
![Screenshot from 2024-12-28 00 57 17](https://github.com/user-attachments/assets/06309eb3-f7a6-46d6-b583-948b94750a3d)

**Comment by warp-core** [comment]
I think you might be in the wrong repository. This repository is focused on the associated wiki, not the game itself. Issues with game content or code should be directed to https://github.com/endless-sky/endless-sky/issues.

Regardless, those outfit are indeed defined in "data/hai outfits.txt":

https://github.com/endless-sky/endless-sky/blob/d5d38334456c7a18ee35e767416d2fdd017a2ffe/data/hai/hai%20outfits.txt#L714-L757

The reason you need weapon space to install them is because of the idea that reverse thrusters are installed at the front of a ship, facing forwards, instead of at the back, facing backwards. So, instead of engine space, they use weapon space.

This is described in the descriptions of the three human reverse thrusters:

https://github.com/endless-sky/endless-sky/blob/d5d38334456c7a18ee35e767416d2fdd017a2ffe/data/human/engines.txt#L320
https://github.com/endless-sky/endless-sky/blob/d5d38334456c7a18ee35e767416d2fdd017a2ffe/data/human/engines.txt#L522
https://github.com/endless-sky/endless-sky/blob/d5d38334456c7a18ee35e767416d2fdd017a2ffe/data/human/engines.txt#L714

> Because a reverse thruster must be facing forwards, it must be installed in the weapon section of your ship instead of the engine section.

Perhaps this should also be added to the Hai reverse thrusters.

**Comment by Naasaan** [comment]
Thank you for the clarification.

I hereby stand corrected. 

;)
